use crate::entity::RuntimeId;
use crate::CoreError;
use std::path::{Path, PathBuf};

/// CLAUDE.md that imports the agent's canonical memory (absolute paths, since
/// memory lives outside the worktree). Regenerated before every spawn.
///
/// `memory_dir` must be an absolute path without whitespace (validated by `write_bridges`).
pub fn claude_bridge(agent_name: &str, memory_dir: &Path) -> String {
    let m = memory_dir.display();
    format!(
        "# {agent_name} — damon agent\n\n\
         Generated by damon; do not edit (edits are overwritten on next session).\n\
         Canonical memory lives at {m}/ — edit there.\n\n\
         @{m}/AGENT.md\n@{m}/USER.md\n@{m}/MEMORY.md\n\n\
         Skills you have written for yourself live in {m}/skills/ — read a\n\
         SKILL.md when its topic is relevant. Follow the write-back protocol\n\
         in MEMORY.md; before finishing a session, update memory and skills.\n"
    )
}

pub fn write_bridges(
    runtime: RuntimeId,
    agent_name: &str,
    memory_dir: &Path,
    worktree: &Path,
) -> Result<Vec<PathBuf>, CoreError> {
    if memory_dir.to_string_lossy().chars().any(char::is_whitespace) {
        return Err(CoreError::Invalid(format!(
            "memory path {:?} contains whitespace; Claude Code @imports cannot express it — use a data root without spaces",
            memory_dir
        )));
    }
    match runtime {
        RuntimeId::Claude => {
            let path = worktree.join("CLAUDE.md");
            std::fs::write(&path, claude_bridge(agent_name, memory_dir))
                .map_err(|e| CoreError::Io { path: path.clone(), source: e })?;
            Ok(vec![path])
        }
        other => Err(CoreError::Invalid(format!(
            "runtime {} not yet supported (M2)",
            other.as_str()
        ))),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::entity::RuntimeId;

    #[test]
    fn claude_bridge_imports_memory_absolutely() {
        let content = claude_bridge("Scout", std::path::Path::new("/mem"));
        assert!(content.contains("# Scout — damon agent"));
        for f in ["AGENT.md", "USER.md", "MEMORY.md"] {
            assert!(content.contains(&format!("@/mem/{f}")), "{f}");
        }
        assert!(content.contains("skills"));
    }

    #[test]
    fn write_bridges_creates_claude_md_and_lists_it() {
        let tmp = tempfile::tempdir().unwrap();
        let written =
            write_bridges(RuntimeId::Claude, "Scout", std::path::Path::new("/mem"), tmp.path()).unwrap();
        assert_eq!(written, vec![tmp.path().join("CLAUDE.md")]);
        assert!(tmp.path().join("CLAUDE.md").exists());
    }

    #[test]
    fn other_runtimes_fail_until_m2() {
        let tmp = tempfile::tempdir().unwrap();
        let err = write_bridges(RuntimeId::Codex, "S", std::path::Path::new("/m"), tmp.path());
        assert!(err.unwrap_err().to_string().contains("M2"));
    }

    #[test]
    fn write_bridges_rejects_whitespace_memory_path() {
        let tmp = tempfile::tempdir().unwrap();
        let err = write_bridges(RuntimeId::Claude, "S", std::path::Path::new("/me m"), tmp.path());
        assert!(err.unwrap_err().to_string().contains("whitespace"));
    }
}
