use crate::entity::RuntimeId;
use crate::CoreError;
use std::path::{Path, PathBuf};

/// CLAUDE.md that imports the agent's canonical memory (absolute paths, since
/// memory lives outside the worktree). Regenerated before every spawn.
///
/// `memory_dir` must be an absolute path without whitespace (validated by `write_bridges`).
pub fn claude_bridge(agent_name: &str, memory_dir: &Path) -> String {
    let m = memory_dir.display();
    format!(
        "# {agent_name} — damon agent\n\n\
         Generated by damon; do not edit (edits are overwritten on next session).\n\
         Canonical memory lives at {m}/ — edit there.\n\n\
         @{m}/AGENT.md\n@{m}/USER.md\n@{m}/MEMORY.md\n\n\
         Skills you have written for yourself live in {m}/skills/ — read a\n\
         SKILL.md when its topic is relevant. Follow the write-back protocol\n\
         in MEMORY.md; before finishing a session, update memory and skills.\n"
    )
}

pub fn embedded_bridge(runtime_label: &str, agent_name: &str, memory_dir: &Path) -> String {
    let path = memory_dir.display();
    let agent = read_memory_file(&memory_dir.join("AGENT.md"));
    let user = read_memory_file(&memory_dir.join("USER.md"));
    let memory = read_memory_file(&memory_dir.join("MEMORY.md"));
    format!(
        "# {agent_name} — Damon {runtime_label} agent\n\n\
         Canonical memory is embedded below because {runtime_label} has no import\n\
         mechanism from outside the worktree.\n\n\
         ## Memory source\n\n\
         Memory root: {path}\n\n\
         ## AGENT.md\n{agent}\n\n\
         ## USER.md\n{user}\n\n\
         ## MEMORY.md\n{memory}\n\n\
         ## Skills\n\n\
         Read and apply instructions from {path}/skills/. Keep memory and\n\
         `skills/*/SKILL.md` aligned with what you learn during the session.\n"
    )
}

fn read_memory_file(path: &Path) -> String {
    std::fs::read_to_string(path).unwrap_or_else(|_| "(missing)\n".into())
}

pub fn write_bridges(
    runtime: RuntimeId,
    agent_name: &str,
    memory_dir: &Path,
    worktree: &Path,
) -> Result<Vec<PathBuf>, CoreError> {
    match runtime {
        RuntimeId::Claude => {
            if memory_dir
                .to_string_lossy()
                .chars()
                .any(char::is_whitespace)
            {
                return Err(CoreError::Invalid(format!(
                    "memory path {:?} contains whitespace; Claude Code @imports cannot express it — use a data root without spaces",
                    memory_dir
                )));
            }
            let path = worktree.join("CLAUDE.md");
            std::fs::write(&path, claude_bridge(agent_name, memory_dir)).map_err(|e| {
                CoreError::Io {
                    path: path.clone(),
                    source: e,
                }
            })?;
            Ok(vec![path])
        }
        RuntimeId::Codex => {
            let path = worktree.join("AGENTS.md");
            std::fs::write(&path, embedded_bridge("Codex", agent_name, memory_dir)).map_err(|e| {
                CoreError::Io {
                    path: path.clone(),
                    source: e,
                }
            })?;
            Ok(vec![path])
        }
        RuntimeId::Opencode => {
            let path = worktree.join("AGENTS.md");
            std::fs::write(&path, embedded_bridge("OpenCode", agent_name, memory_dir)).map_err(|e| {
                CoreError::Io {
                    path: path.clone(),
                    source: e,
                }
            })?;
            Ok(vec![path])
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::entity::RuntimeId;

    #[test]
    fn claude_bridge_imports_memory_absolutely() {
        let content = claude_bridge("Scout", std::path::Path::new("/mem"));
        assert!(content.contains("# Scout — damon agent"));
        for f in ["AGENT.md", "USER.md", "MEMORY.md"] {
            assert!(content.contains(&format!("@/mem/{f}")), "{f}");
        }
        assert!(content.contains("skills"));
    }

    #[test]
    fn write_bridges_creates_claude_md_and_lists_it() {
        let tmp = tempfile::tempdir().unwrap();
        let written = write_bridges(
            RuntimeId::Claude,
            "Scout",
            std::path::Path::new("/mem"),
            tmp.path(),
        )
        .unwrap();
        assert_eq!(written, vec![tmp.path().join("CLAUDE.md")]);
        assert!(tmp.path().join("CLAUDE.md").exists());
    }

    #[test]
    fn codex_bridge_embeds_memory() {
        let tmp = tempfile::tempdir().unwrap();
        let memory = tmp.path().join("memory");
        std::fs::create_dir_all(&memory).unwrap();
        std::fs::write(memory.join("AGENT.md"), "agent").unwrap();
        std::fs::write(memory.join("USER.md"), "user").unwrap();
        std::fs::write(memory.join("MEMORY.md"), "memory").unwrap();
        let written = write_bridges(RuntimeId::Codex, "Scout", &memory, tmp.path()).unwrap();
        assert_eq!(written, vec![tmp.path().join("AGENTS.md")]);
        let contents = std::fs::read_to_string(tmp.path().join("AGENTS.md")).unwrap();
        assert!(contents.contains("# Scout — Damon Codex agent"));
        assert!(contents.contains("agent"));
        assert!(contents.contains("user"));
        assert!(contents.contains("memory"));
    }

    #[test]
    fn opencode_bridge_embeds_memory() {
        let tmp = tempfile::tempdir().unwrap();
        let memory = tmp.path().join("memory");
        std::fs::create_dir_all(&memory).unwrap();
        std::fs::write(memory.join("AGENT.md"), "agent").unwrap();
        std::fs::write(memory.join("USER.md"), "user").unwrap();
        std::fs::write(memory.join("MEMORY.md"), "memory").unwrap();
        let written = write_bridges(RuntimeId::Opencode, "Scout", &memory, tmp.path()).unwrap();
        assert_eq!(written, vec![tmp.path().join("AGENTS.md")]);
        let contents = std::fs::read_to_string(tmp.path().join("AGENTS.md")).unwrap();
        assert!(contents.contains("# Scout — Damon OpenCode agent"));
        assert!(contents.contains("agent"));
        assert!(contents.contains("user"));
        assert!(contents.contains("memory"));
    }

    #[test]
    fn write_bridges_rejects_whitespace_memory_path() {
        let tmp = tempfile::tempdir().unwrap();
        let err = write_bridges(
            RuntimeId::Claude,
            "S",
            std::path::Path::new("/me m"),
            tmp.path(),
        );
        assert!(err.unwrap_err().to_string().contains("whitespace"));
    }
}
