use crate::entity::RuntimeId;
use crate::CoreError;
use std::path::{Path, PathBuf};

/// CLAUDE.md that imports the agent's canonical memory (absolute paths, since
/// memory lives outside the worktree). Regenerated before every spawn.
///
/// `memory_dir` must be an absolute path without whitespace (validated by `write_bridges`).
pub fn claude_bridge(agent_name: &str, memory_dir: &Path) -> String {
    let m = memory_dir.display();
    format!(
        "# {agent_name} — cortado agent\n\n\
         Generated by cortado; do not edit (edits are overwritten on next session).\n\
         Canonical memory lives at {m}/ — edit there.\n\n\
         @{m}/AGENT.md\n@{m}/USER.md\n@{m}/MEMORY.md\n\n\
         Skills you have written for yourself live in {m}/skills/ — read a\n\
         SKILL.md when its topic is relevant. Follow the write-back protocol\n\
         in MEMORY.md; before finishing a session, update memory and skills.\n"
    )
}

pub fn embedded_bridge(runtime_label: &str, agent_name: &str, memory_dir: &Path) -> String {
    let path = memory_dir.display();
    let agent = read_memory_file(&memory_dir.join("AGENT.md"));
    let user = read_memory_file(&memory_dir.join("USER.md"));
    let memory = read_memory_file(&memory_dir.join("MEMORY.md"));
    format!(
        "# {agent_name} — Cortado {runtime_label} agent\n\n\
         Canonical memory is embedded below because {runtime_label} has no import\n\
         mechanism from outside the worktree.\n\n\
         ## Memory source\n\n\
         Memory root: {path}\n\n\
         ## AGENT.md\n{agent}\n\n\
         ## USER.md\n{user}\n\n\
         ## MEMORY.md\n{memory}\n\n\
         ## Skills\n\n\
         Read and apply instructions from {path}/skills/. Keep memory and\n\
         `skills/*/SKILL.md` aligned with what you learn during the session.\n"
    )
}

fn read_memory_file(path: &Path) -> String {
    std::fs::read_to_string(path).unwrap_or_else(|_| "(missing)\n".into())
}

/// Same-directory temp file + rename: a reader (or a crash) never observes a
/// half-written bridge file. The CLAUDE.md/settings.json PAIR stays
/// non-transactional by design — bridges regenerate before every spawn.
fn write_atomic(path: &Path, content: &str) -> Result<(), CoreError> {
    let io = |p: &Path, e: std::io::Error| CoreError::Io {
        path: p.to_path_buf(),
        source: e,
    };
    let (parent, file_name) = match (path.parent(), path.file_name().and_then(|n| n.to_str())) {
        (Some(p), Some(n)) => (p, n),
        _ => {
            return Err(CoreError::Invalid(format!(
                "bad bridge path {}",
                path.display()
            )))
        }
    };
    let tmp = parent.join(format!(".{file_name}.cortado-tmp"));
    std::fs::write(&tmp, content).map_err(|e| io(&tmp, e))?;
    if let Err(e) = std::fs::rename(&tmp, path) {
        // Best-effort cleanup; the rename error is still the one reported.
        let _ = std::fs::remove_file(&tmp);
        return Err(io(path, e));
    }
    Ok(())
}

#[derive(Debug, PartialEq)]
pub struct BridgeOutput {
    pub written: Vec<PathBuf>,
    pub warnings: Vec<String>,
}

pub fn write_bridges(
    runtime: RuntimeId,
    agent_name: &str,
    memory_dir: &Path,
    worktree: &Path,
    cortado_exe: &str,
) -> Result<BridgeOutput, CoreError> {
    match runtime {
        RuntimeId::Claude => {
            if memory_dir
                .to_string_lossy()
                .chars()
                .any(char::is_whitespace)
            {
                return Err(CoreError::Invalid(format!(
                    "memory path {:?} contains whitespace; Claude Code @imports cannot express it — use a data root without spaces",
                    memory_dir
                )));
            }
            let path = worktree.join("CLAUDE.md");
            write_atomic(&path, &claude_bridge(agent_name, memory_dir))?;
            let mut written = vec![path];

            // The Stop hook command embeds `cortado_exe` inside a JSON string that
            // is itself run as a shell command by Claude Code.
            //
            // JSON safety: serde_json::json! escapes all special characters (quotes,
            // backslashes, etc.) correctly, so exotic exe paths like `/tmp/we"ird/cortado`
            // produce valid JSON.
            let mut warnings = Vec::new();
            if cortado_exe.chars().any(char::is_whitespace) {
                // Whitespace guard: A path containing whitespace would break the shell
                // command line itself (the JSON is later executed by Claude Code), so we
                // skip writing settings.json in that case — the Stop hook is an
                // enhancement (session-end reflection), not correctness, so degrading
                // gracefully beats emitting a broken hook.
                warnings.push(format!(
                    "cortado executable path {cortado_exe:?} contains whitespace; \
                     skipping the session-end reflection hook (.claude/settings.json)"
                ));
            } else {
                let settings_dir = worktree.join(".claude");
                std::fs::create_dir_all(&settings_dir).map_err(|e| CoreError::Io {
                    path: settings_dir.clone(),
                    source: e,
                })?;
                let settings = settings_dir.join("settings.json");
                let content = serde_json::json!({
                    "hooks": {
                        "Stop": [
                            { "hooks": [ { "type": "command", "command": format!("{cortado_exe} hook reflect") } ] }
                        ]
                    }
                });
                let content = format!("{:#}\n", content);
                write_atomic(&settings, &content)?;
                written.push(settings);
            }

            Ok(BridgeOutput { written, warnings })
        }
        RuntimeId::Codex => {
            let path = worktree.join("AGENTS.md");
            write_atomic(&path, &embedded_bridge("Codex", agent_name, memory_dir))?;
            Ok(BridgeOutput {
                written: vec![path],
                warnings: Vec::new(),
            })
        }
        RuntimeId::Opencode => {
            let path = worktree.join("AGENTS.md");
            write_atomic(&path, &embedded_bridge("OpenCode", agent_name, memory_dir))?;
            Ok(BridgeOutput {
                written: vec![path],
                warnings: Vec::new(),
            })
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::entity::RuntimeId;

    #[test]
    fn claude_bridge_imports_memory_absolutely() {
        let content = claude_bridge("Scout", std::path::Path::new("/mem"));
        assert!(content.contains("# Scout — cortado agent"));
        for f in ["AGENT.md", "USER.md", "MEMORY.md"] {
            assert!(content.contains(&format!("@/mem/{f}")), "{f}");
        }
        assert!(content.contains("skills"));
    }

    #[test]
    fn write_bridges_creates_claude_md_and_settings_and_lists_both() {
        let tmp = tempfile::tempdir().unwrap();
        let out = write_bridges(
            RuntimeId::Claude,
            "Scout",
            std::path::Path::new("/mem"),
            tmp.path(),
            "cortado",
        )
        .unwrap();
        assert_eq!(
            out.written,
            vec![
                tmp.path().join("CLAUDE.md"),
                tmp.path().join(".claude/settings.json"),
            ]
        );
        assert!(tmp.path().join("CLAUDE.md").exists());
        let settings = std::fs::read_to_string(tmp.path().join(".claude/settings.json")).unwrap();
        assert!(settings.contains("\"Stop\""));
        assert!(settings.contains("cortado hook reflect"));
    }

    #[test]
    fn write_bridges_skips_settings_when_cortado_exe_has_whitespace() {
        let tmp = tempfile::tempdir().unwrap();
        let out = write_bridges(
            RuntimeId::Claude,
            "Scout",
            std::path::Path::new("/mem"),
            tmp.path(),
            "/path with space/cortado",
        )
        .unwrap();
        assert_eq!(out.written, vec![tmp.path().join("CLAUDE.md")]);
        assert_eq!(out.warnings.len(), 1);
        assert!(!tmp.path().join(".claude/settings.json").exists());
    }

    #[test]
    fn codex_bridge_embeds_memory() {
        let tmp = tempfile::tempdir().unwrap();
        let memory = tmp.path().join("memory");
        std::fs::create_dir_all(&memory).unwrap();
        std::fs::write(memory.join("AGENT.md"), "agent").unwrap();
        std::fs::write(memory.join("USER.md"), "user").unwrap();
        std::fs::write(memory.join("MEMORY.md"), "memory").unwrap();
        let out = write_bridges(RuntimeId::Codex, "Scout", &memory, tmp.path(), "cortado").unwrap();
        assert_eq!(out.written, vec![tmp.path().join("AGENTS.md")]);
        let contents = std::fs::read_to_string(tmp.path().join("AGENTS.md")).unwrap();
        assert!(contents.contains("# Scout — Cortado Codex agent"));
        assert!(contents.contains("agent"));
        assert!(contents.contains("user"));
        assert!(contents.contains("memory"));
    }

    #[test]
    fn opencode_bridge_embeds_memory() {
        let tmp = tempfile::tempdir().unwrap();
        let memory = tmp.path().join("memory");
        std::fs::create_dir_all(&memory).unwrap();
        std::fs::write(memory.join("AGENT.md"), "agent").unwrap();
        std::fs::write(memory.join("USER.md"), "user").unwrap();
        std::fs::write(memory.join("MEMORY.md"), "memory").unwrap();
        let out =
            write_bridges(RuntimeId::Opencode, "Scout", &memory, tmp.path(), "cortado").unwrap();
        assert_eq!(out.written, vec![tmp.path().join("AGENTS.md")]);
        let contents = std::fs::read_to_string(tmp.path().join("AGENTS.md")).unwrap();
        assert!(contents.contains("# Scout — Cortado OpenCode agent"));
        assert!(contents.contains("agent"));
        assert!(contents.contains("user"));
        assert!(contents.contains("memory"));
    }

    #[test]
    fn write_bridges_rejects_whitespace_memory_path() {
        let tmp = tempfile::tempdir().unwrap();
        let err = write_bridges(
            RuntimeId::Claude,
            "S",
            std::path::Path::new("/me m"),
            tmp.path(),
            "cortado",
        );
        assert!(err.unwrap_err().to_string().contains("whitespace"));
    }

    #[test]
    fn write_bridges_escapes_quotes_in_exe_path() {
        let tmp = tempfile::tempdir().unwrap();
        let out = write_bridges(
            RuntimeId::Claude,
            "Scout",
            std::path::Path::new("/mem"),
            tmp.path(),
            "/tmp/we\"ird/cortado",
        )
        .unwrap();
        assert_eq!(
            out.written,
            vec![
                tmp.path().join("CLAUDE.md"),
                tmp.path().join(".claude/settings.json"),
            ]
        );
        let settings = std::fs::read_to_string(tmp.path().join(".claude/settings.json")).unwrap();

        // Verify the JSON is valid by parsing it
        let parsed: serde_json::Value = serde_json::from_str(&settings)
            .expect("settings.json should be valid JSON even with quotes in exe path");

        // Verify the command field contains the raw path (with escaped quotes in the JSON)
        let command = parsed["hooks"]["Stop"][0]["hooks"][0]["command"]
            .as_str()
            .expect("command should be a string");
        assert!(command.contains("/tmp/we\"ird/cortado hook reflect"));
    }

    #[test]
    fn bridge_writes_leave_no_temp_files() {
        let tmp = tempfile::tempdir().unwrap();
        write_bridges(
            RuntimeId::Claude,
            "Scout",
            std::path::Path::new("/mem"),
            tmp.path(),
            "cortado",
        )
        .unwrap();
        let leftovers: Vec<_> = walk_files(tmp.path())
            .into_iter()
            .filter(|p| p.to_string_lossy().contains("cortado-tmp"))
            .collect();
        assert!(leftovers.is_empty(), "{leftovers:?}");
    }

    #[test]
    fn bridge_writes_overwrite_existing_files() {
        let tmp = tempfile::tempdir().unwrap();
        std::fs::write(tmp.path().join("CLAUDE.md"), "stale").unwrap();
        write_bridges(
            RuntimeId::Claude,
            "Scout",
            std::path::Path::new("/mem"),
            tmp.path(),
            "cortado",
        )
        .unwrap();
        let content = std::fs::read_to_string(tmp.path().join("CLAUDE.md")).unwrap();
        assert!(content.contains("# Scout — cortado agent"));
    }

    #[test]
    fn skipping_the_hook_warns_instead_of_silence() {
        let tmp = tempfile::tempdir().unwrap();
        let out = write_bridges(
            RuntimeId::Claude,
            "Scout",
            std::path::Path::new("/mem"),
            tmp.path(),
            "/path with space/cortado",
        )
        .unwrap();
        assert_eq!(out.written, vec![tmp.path().join("CLAUDE.md")]);
        assert_eq!(out.warnings.len(), 1);
        assert!(out.warnings[0].contains("reflection hook"));
        assert!(out.warnings[0].contains("whitespace"));
    }

    fn walk_files(dir: &std::path::Path) -> Vec<std::path::PathBuf> {
        let mut out = Vec::new();
        for entry in std::fs::read_dir(dir).unwrap().flatten() {
            if entry.path().is_dir() {
                out.extend(walk_files(&entry.path()));
            } else {
                out.push(entry.path());
            }
        }
        out
    }

    #[test]
    fn codex_bridge_handles_whitespace_memory_path() {
        let tmp = tempfile::tempdir().unwrap();
        let memory = tmp.path().join("mem ory");
        std::fs::create_dir_all(&memory).unwrap();
        std::fs::write(memory.join("AGENT.md"), "agent-content").unwrap();
        std::fs::write(memory.join("USER.md"), "user-content").unwrap();
        std::fs::write(memory.join("MEMORY.md"), "memory-content").unwrap();
        let out = write_bridges(RuntimeId::Codex, "Scout", &memory, tmp.path(), "cortado").unwrap();
        assert_eq!(out.written, vec![tmp.path().join("AGENTS.md")]);
        assert!(out.warnings.is_empty());
        let contents = std::fs::read_to_string(tmp.path().join("AGENTS.md")).unwrap();
        assert!(contents.contains("agent-content"));
        assert!(contents.contains("mem ory")); // path is embedded verbatim, not imported
    }

    #[test]
    fn failed_atomic_write_cleans_up_temp_file() {
        let tmp = tempfile::tempdir().unwrap();
        // A directory at the destination makes the rename step fail.
        let dest = tmp.path().join("CLAUDE.md");
        std::fs::create_dir_all(&dest).unwrap();
        assert!(write_atomic(&dest, "content").is_err());
        let leftovers: Vec<String> = std::fs::read_dir(tmp.path())
            .unwrap()
            .flatten()
            .map(|e| e.file_name().to_string_lossy().into_owned())
            .filter(|n| n.contains("cortado-tmp"))
            .collect();
        assert!(leftovers.is_empty(), "{leftovers:?}");
    }
}
